services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq-host
    ports:
      - "10072:5672"
      - "10081:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin@123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

  mongodb:
    image: mongo:7
    ports:
      - "10017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - TZ=America/Sao_Paulo

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "10082:8081"
    depends_on:
      - mongodb

volumes:
  rabbitmq_data:
  mongo_data:
