version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq-host
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin@123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

volumes:
  rabbitmq_data:
